
[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.92
decorations = "Buttonless"
startup_mode = "Maximized"
dynamic_title = true
blur = false

[window.padding]
x = 10
y = 10

[colors]
draw_bold_text_with_bright_colors = true

[mouse]
hide_when_typing = true

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/theme/tokyonight.toml"
]
